baseURL: 'https://simon.duchastel.com/'
languageCode: 'en-us'
title: "Simon Duchastel"
pagination:
  pagerSize: 10
theme: "PaperMod"


enableRobotsTXT: true
taxonomies:
  # override taxonimies with just 'cateogeries' so that a 'tags' page isn't generated
  # by default, 'tags' and 'categories' are both generated but I only want 'categories'
  category: categories

params:
  env: production
  description: "Simon Duchastel - Software Engineer | Scifi Fan | Transit Enthusiast"
  showCodeCopyButtons: true
  profileMode:
      enabled: true
      title: "Simon Duchastel"
      subtitle: "Software Engineer | Scifi Fan | Transit Enthusiast"
  socialIcons:
      - name: "github"
        url: "https://github.com/simon-duchastel"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/simonduchastel/"
      - name: "hardcover"
        url: "https://hardcover.app/@simonduchastel"

menu:
  main:
    - name: Posts
      url: "/posts"
      weight: 10
    - name: "About Me"
      url: "/about"
      weight: 20
    - name: Resume
      url: "/resume.pdf"
      weight: 30
      params:
        external: true
